DeveloperAcademy-POSTECH/MacC-TEAM-8bit

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataClass.swift, OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataProperties.swift, OrrRock/OrrRock/OrrRock.xcdatamodeld/OrrRock.xcdatamodel/contents
1. 영상 정보 Data Model, VideoInformation 구조 작성
2. 프로젝트 파일에 Core Data Model 추가
|기본 데이터 구조 정보|
|:---:|
|<img width="700" alt="스크린샷 2022-10-20 오후 4 30 11" src="https://user-images.githubusercontent.com/96641477/196884529-a80c7fe1-a87e-435c-a5e3-3d00595a34a5.png">|
- #9 
|Core Data Model|
|:---:|
|<img width="534" alt="스크린샷 2022-10-20 오후 4 31 30" src="https://user-images.githubusercontent.com/96641477/196884786-55fcaefc-abe5-4fe4-8cc3-6ae781a012e4.png">|
- Level이 20 이상보다 높을 가능성은 없다고 생각하여 `problemLevel`은 `Int16(범위값:  -32768 to 32767)`으로 지정했습니다.
-> 추후 기본 Int 자료형에서 형변환이 번거롭다고 판단될 경우, 변경될 여지가 존재합니다.
|파일 추가|
|:---:|
|<img width="265" alt="스크린샷 2022-10-20 오후 4 27 52" src="https://user-images.githubusercontent.com/96641477/196883980-3aa7a1de-2f40-4d0f-b841-d904c5cf3c7c.png">|
- extension 추후 …
=> [#9] feat - Core Data Model 추가

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift, OrrRock/OrrRock/Models/CoreData/VideoInfo.swift
1. CoreData Entity의 편리한 추가를 위한 Struct `VideoInfo` 작성
2. CoreDataManager 기본 싱글톤 클래스 작성
3. CoreData Entity 생성 메소드 만들기
- #14 
- CoreData Entity의 편리한 추가를 위한 Struct의 구조는 **VideoInfo.swift**에서 확인가능합니다.
- VideoInfo 구조체의 경우, 데이터 만들어서 추가하는 경우에만 사용되는 모델로 작성했기 때문에 현재 Initializer는 구조체의 모든 Property를 직접 할당하지는 않습니다.
- 직접 할당하지 않는 데이터: isFavorite(즐겨찾기 항목), feedback(문제에 대한 피드백)
- Core Data 데이터 추가를 위한 메소드 ```func createData(info: VideoInfo)```와 추가된 데이터를 context 반영하기 위한 메소드 ```func saveData()```는 **CoreDataManager.swift**에서 확인가능합니다.
- 작업의 결과물이 따로 존재하지 않는 경우에는 기록 X
- 데이터 생성 메소드만으로는 테스트할 수 있는 예시가 존재하지 않기 때문에 추후 #15 구현 후 테스트가 가능합니다.
Q. VideoInfo 구조체의 추가적인 Initializer가 필요할까요? 현재 데이터 모델에서 사용될 것이라고 추측되는 Initializer는 이번 Issue에서 작성한 해당 init이지만, 여러 케이스를 고려해 전체 프로퍼티를 직접 할당하는 Initializer도 작성하면 좋을지에 대해 팀원분들의 의견이 궁금합니다! …
=> [#14] feat - CoreDataManager 구현: CREAT

OrrRock/OrrRock/SceneDelegate.swift, OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
1. HomeViewController에 제가 기존에 만든 로직을 추가했습니다.
- #17
- 제 기기에서 동작하는 영상은 개인 정보 문제로 시뮬레이터로 대체 합니다.
https://user-images.githubusercontent.com/103024840/197003018-078d8e9f-91fc-4d3c-8858-80d2999c5676.mov
- 화이트 스페이싱등 코드를 정렬하고 싶었으나
- 해당 뷰를 레드도 작업하고 있어 최대한 수정하지 않았습니다.
이번에 작성한 코드에 NSLog를 사용하게 되서 간단하게 설명해보겠습니다.
영상을 가져오는 과정에서 에러를 NSLog로 찍고 있는데 이유는 다음과 같습니다.
비교를 위해 정상동작 print와 NSLog를 같이 출력해볼게요.
Xcode에서 확인해보면
날자값이 추가된것이 NSLog입니다.
이렇게만 보면 별 차이가 없는데 왜 NSLog를 사용할까요?
단순히 날짜만 보려고 사용 하는것은 아닙니다.
아래보이는 화면은 아이폰에서 찍히는 모든 로그를 볼 수 있는 창입니다.
내용을 보면 TestLog는 보이나 TestPrint는 보이지 않습니다.
네 print는 저기에 출력되지 않아요.
추가적으로 사용자 혹은 특정 아이폰에서 테스트를 하다가 오류가 발견되었을 때 콘솔에 연결해서 관제하면 바로 오류 로그를 볼 수있습니다.
제가 여기서 사용한 것은 제가 작성한 코드가 에러 상황을 발생시키지 못하였지만 
일단 예외처리는 필요하다는 리뷰를 받아 예외처리를 했고 해당 이슈 발생시 
사용자의 폰을 사용해 어떤 오류인지 바로 확인하려고 추가했습니다.!!
Close #17
=> [#17] feat -  HomeVeiwController에 기존 로직 추가

OrrRock/OrrRock/Assets.xcassets/Colors/oRGray2.colorset/Contents.json, OrrRock/OrrRock/Assets.xcassets/Colors/oRGray3.colorset/Contents.json, OrrRock/OrrRock/Assets.xcassets/Colors/oRGray4.colorset/Contents.json, OrrRock/OrrRock/Extensions/Color+.swift
1. 컬러명 수정
- #22
- orrGray2 가 추가 되었습니다.
- 추후 다크모드 생성시 제가 추가한 모든 색상에 라이트 다크 모드 구분 하여 색상 추가 가능합니다.
Close #22
=> [#22] fix - 컬러명을 수정 

OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
1. 겹쳐지는 것 처럼 보이는 영상 텍스트 부분이랑 하단 버튼 사이에 패딩값을 주는 작업
- #101 
- 텍스트가 5줄 이상이 되었을 때 날짜, 암장을 보여주는 뷰와 겹치지 않게 패딩값을 준 부분 확인 부탁드립니다.
Close #101
=> [#101] fix - 피드백 글자와 날짜 정보 겹쳐짐

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Models/UploadModels/SwipeableCardModel/SwipeableCardVideoModel.swift, OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardVideoView.swift, OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
1. 영상 분류시 테두리가 추가되었습니다.
2. 상황에 따라 색상이 유동적으로 변경됩니다.
- #102 
영상의 용량이커서 사진으로 대체 합니다.
|성공일때|중립일때(흰색)|실패일때|
|---|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/200361237-0b6cbd1a-9e6d-4801-a7c7-a9dae20ace5a.jpeg">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/200361262-c22e256c-d562-443b-9691-7ebebe829407.jpeg">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/200361268-64a0e5eb-9998-4860-afc7-18419a588a6c.jpeg">|
- 생각보다 금방 끝나서 다행이에요.
- 사랑해요
Close #102
=> [#102] fix 영상테두리추가

OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardVideoView.swift, OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
1. 데이터 유실 원인 파악 및 해결
2. 기능만 구현해 놓은 코드 리팩토링
3. 기존 영상이 반복재생이 되지 않던 문제 해결
- #106 
- 사진에서 보이다시피 `requestAVAsset` [메서드](https://developer.apple.com/documentation/photokit/phimagemanager/1616935-requestavasset)를 통해 비동기적으로 데이터가 넘어오는 과정에서 몇몇 Asset이 (x 표시가 된 부분) nil값이 넘어옴  
- `requestAVAsset` 메서드 특성 상 비동기 요청의 경우, Photos는 resultHandler블록을 두번 이상 호출 할 수 있음  
- 그 과정에서 nil 값이 넘어왔을 때 `guard let`에서 return 해버려서 Asset 데이터가 유실됨  
- 클라우드와 동기화가 되어 있는 Asset의 경우 간헐적으로 한번 호출로는 nil 값이 넘어옴  
-  `PHVideoRequestOptions`을 따로  설정해 주지 않으면 `isNetworkAccessAllowed` [값이 디폴트로 false로 지정](https://developer.apple.com/documentation/photokit/phimagerequestoptions/1616934-isnetworkaccessallowed)되어 있음
- `true`로 지정해 주었을 때 동기화가 되어있는 Asset도 정상적으로 넘어옴  
- 기존에 `totalCount`로 Asset의 수를 체크했던 코드를 `DispatchGroup`을 통한 Reference Counting으로 …
=> [#106] fix - 영상 분류 완료 로직 개선

OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift, OrrRock/OrrRock/Views/VideoDetailView/VideoPlayView.swift
1. VideoDetailView에서 영상이 없는 경우에 영상 대신 "앨범에서 영상이 삭제되어 해당 영상을 재생할 수 없습니다." PlaceHolder를 보여줌.
2. 삭제된 영상에 대한 썸네일은 예외처리를 통해 기본 PlaceHolder Color를 보여줌.
- #121
|영상 없는 HomeView|영상 없는 CollectionView|영상 없는 DetailView|전체화면 모드에서|
|---|---|---|---|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-11-08 at 16 39 02](https://user-images.githubusercontent.com/39216546/200506068-415d990f-3e3b-4393-8caf-c17784578494.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-11-08 at 16 39 09](https://user-images.githubusercontent.com/39216546/200506774-ec9a5d13-63e4-4ca5-a40d-7b599104ed2d.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-11-08 at 16 39 12](https://user-images.githubusercontent.com/39216546/200506544-df4573f0-1634-4025-8fd5-c587c0cd2bcd.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-11-08 at …
=> [#121] fix - 영상이 삭제된 경우에 VideoDetailView 예외처리

OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift, OrrRock/OrrRock/Views/HomeView/HomeCollectionViewListCell.swift
홈화면 목록형으로 볼때 썸네일 깨짐 수정
cornerRadius 미적용 이슈 해결
- #129
|기존|개선|
|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/200599209-e964a9c4-8850-4f22-953f-80182ba3cf31.PNG">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/200599252-f019f860-0c5b-44fb-a868-ef15bd3d0e3d.PNG">|
- 야근은 있어서 한계는 없습니다.
- 몇줄 수정 안했습니당!!
Close #129
=> [#129] fix 홈화면 목록형으로 볼때 썸네일 깨짐 수정

OrrRock/OrrRock/Upload/DateSettingViewController.swift
1. DateSettingView nextButton bottom padding 추가 
- #145 
|홈버튼 없는 모델|홈버튼이 있는모델|
|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201517273-3eb62d37-4a6b-47bd-9932-8927ae834ab2.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201517137-e2304952-45c4-4196-8150-f2894d3ac4b2.png">|
|13ProMax|SE3|
|홈버튼 없는 모델|홈버튼이 있는모델|
|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201517293-03703714-674e-42d1-beb3-edfc50f4fb86.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201517022-2f472053-3dd8-4b90-941b-76eb4e37ac8a.png">|
|13ProMax|SE3|
- 린다에게 컨펌후 머지 예정
- 화이팅 :D
Close #145
=> [#145] fix add DateSettingView nextButton bottom padding

OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
1. LevelAndPFSettingViewController 오토레이아웃 수정
2. 카드의 비율을 16:9로 고정
3. 하단 이미지 참조
- #147
|홈버튼 없는 모델|홈버튼이 있는모델|
|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201677089-afb8e5c8-8cf2-4d6a-8da6-30180f994e66.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201677177-d528c2be-4d0c-4252-9281-677a8cf46aaa.png">|
|13ProMax|SE3|
|홈버튼 없는 모델|홈버튼이 있는모델|
|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201676906-d0036fce-4260-4963-be4f-8d14dc669c6c.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/103024840/201676766-a4b8b8f7-dfae-4614-a964-878e5653f0bf.png">|
|13ProMax|SE3|
- 저에게 한계란 없습니다.
- 다른 분들도 해당 뷰에 작업이 필요하다고 하셔서 먼저 올립니다.
- 해당 …
=> [#147] fix LevelAndPFSettingViewController 오토레이아웃 수정

OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
1. 원래 이미지 캐싱을 위한 클래스 `PHCachingImageManager`를 상위 오브젝트인 `PHImageManager`로 변경
2. `AVAsset`으로 불러올 수 없어 `nil`값이 호출되는 시점에서 경고창과 함께 뒤로 돌아가도록 구현
- #165 
|기존 상황|변경 상황|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/45965405/201708286-8e518dd7-d869-46fe-a619-2e5fe8d190e0.png"  width="200">|<img src="https://user-images.githubusercontent.com/45965405/201708337-d4222e22-42c7-4f32-8dcf-8cf5ed135efa.png"  width="200">|
|무한 로딩 현상과 함께 다음 동작을 할 수 없음|경고창과 함께 다시 영상을 선택할 수 있음|
- 지금 "슬로우모션비디오"와 "클라우드연동비디오"에 대해 예외 처리를 통해 불러올 수 없는 에러를 수정했으나 
- 다른 예상치 못한 일반적이지 않은 포맷의 영상이 들어올 수도 있다는 판단에 
- `nil` 값이 들어와서 레퍼런스 카운팅이 되지 않아 무한 로딩 현상이 걸릴 수 있을 법한 모든 가능성을 차단하기 위해 이와 같이 구현하였습니다.
- 경고창에 뜨는 문구에 대해서 제가 임의로 작성을 하긴 했는데 다른 좋은 워딩을 함께 고려하면 좋을 것 같습니다.
Close #165
=> [#165] fix - request가 불가능한 영상이 들어왔을 경우 경고창과 함께 뒤로 돌아가는 로직 구현

OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift, OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
1. 디폴트로 카드 재생을 일시정지 상태로 카드를 불러오도록 수정
2. `cards` 배열의 0번째 인덱스의 카드를 재생
3. 스와이프 애니매이션이 끝나면 다음 카드의 영상을 재생
- #171 
|수정 전|수정 후|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/45965405/201926058-1dc54b58-b36a-4648-aac4-9131fca53065.gif"  width="200">|<img src="https://user-images.githubusercontent.com/45965405/201926109-40fe5bff-ef2c-432f-9454-005d676121f9.gif"  width="200">  |
|백그라운드에서 카드 영상이 재생되고 있음|가장 상단에 있는 카드 영상만 재생되고 있음|  
> **테스트 환경**
> - iPhone 12 Pro (A14 칩셋 / 6GB RAM)
> - 4K 60fps HEVC 포맷 30초 HDR 영상
수정 전 : 고용량 영상 5개 부터 프레임 드랍이 발생  
수정 후 : 고용량 영상 20개까지도 프레임 드랍 발생하지 않음
- 고용량 영상을 업로드 하는 과정에서 로딩 시간이 꽤 오래 걸림  
- 테스트 환경 기준 영상 20개 업로드 5초
- 영상은 비동기적으로 불러오기 때문에 영상은 재생은 되지만,  
영상 업로드와 영상 재생이 겹쳐져서 5초정도 영상 끊김이 있음
- 추후 고용량 영상을 업로드하는데 드는 시간을 줄이는 작업도 해야할 것 같아요
Close #171
=> [#171] feat - 영상이 백그라운드에서 재생 정지된 채 로드되고 상단 노출 되었을 때 재생되는 기능 추가

OrrRock/OrrRock/VideoDetail/Cell/VideoCollectionViewCustomCell.swift
1. VideoCollectionView의 하트이미지의 위치를 좌하단에서 우상단으로 변경하였습니다.
- #152
-확인을 위해 하트의 색상을 검정으로 임시 변경하였습니다.(현재는 하양)
- 감사합니다.
Close #152
=> [#152] fix - VideoCollectionView 하트 이미지 위치 조절

OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift, OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
1. 현재 카드 분류 상태 표시 UI 제작
2. 카드 분류 상황을 받아와서 SwipableCard에 띄워 주는 기능 구현
- #166 
|첫번째 카드|뒤의 카드|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/45965405/202432731-65048901-69e6-4f38-84fc-6cee06998019.png"  width="250">|<img src="https://user-images.githubusercontent.com/45965405/202432813-15f28f64-f6e8-48c2-aec6-844294a4398f.png"  width="250">|
- 추후 남은 카드의 수를 보여주는 방식의 디자인이 수정될 가능성 있음
Close #166
=> [#166] feat - 영상 스와이프 뷰에서 총 영상 개수와 남은 영상 개수 띄워주는 작업

OrrRock/OrrRock/Home/Cell/HomeTableViewHeader.swift, OrrRock/OrrRock/Home/HomeViewController.swift
1. HeaderView 크기 수정
2. HeaderView의 Gradient 범위 및 값 수정
3. Gradient 영역 내에 있어도 터치가 가능하도록 상단영역의 UserInteractive 차단
4. 기타 UI detail 수정
- #189 
- 이후에 HeaderView의 UI를 변경하고 싶다면 다음의 작업을 수행해야 합니다!!
- HeaderView 선언부에서 view의 height 변경 (gradient 설정을 위함)
- HeaderView SnapKit layout 지정부에서 height 변경 (기기대응을 위함)
- Gradient 범위 변경 (최상단과 최하단을 [0, 1]로 하여, 비율로 값을 입력)
- 사랑해요
Close #189
=> [#189] design - HomeView UI 수정

OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
1. 목룍형 뷰에서 영상재생뷰로 넘어갈시에 나오던 에러를 해결하였습니다.
- #208 
- 영상재생뷰가 필요로하는 정보가 달라짐에따라 넘겨주는 정보도 수정하였습니다.
- 감사합니다.
Close #208
=> [#208] fix - 목록형 뷰에서 셀 선택시 나오던 에러 해결

OrrRock/OrrRock/SceneDelegate.swift
1. 기존 MainViewController 코드부는 주석처리
2. 1.0.3버전을 위하여 일시적으로 rootVC HomeViewController로 수정
- #234
```
// SceneDelegate.swift
//        window?.rootViewController = UINavigationController(rootViewController: MainViewController())
window?.rootViewController = UINavigationController(rootViewController: HomeViewController())
```
- ♥️
Close #234
=> [#234] hotfix - Release 버전 관리를 위한 UINavigationViewController root뷰 수정

OrrRock/OrrRock/Upload/DateSettingViewController.swift, OrrRock/OrrRock/Upload/GymSettingViewController.swift, OrrRock/OrrRock/Utils/CustomBackBarButtomItem.swift, OrrRock/OrrRock/Utils/UnderlinedTextField.swift, OrrRock/OrrRock/VideoDetail/DateAndGymEditViewController.swift
1. 날짜 선택 뷰 UI 수정
2. 클라이밍장 명 입력 뷰 UI 수정
3. 클라이밍장명 20자 길이 제한 기능 구현
4. VideoCollectionView 내 타이틀이 정중앙을 벗어나지 않도록 개선
- #215 #217 
|날짜 입력 UI|클라이밍장 명 입력 UI + 20자 제한 UI|
|---|---|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/202916659-e7704565-776d-41c8-b421-cd2d26989473.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/202916585-f690d7fb-43dc-4cb2-ab91-9457afc1703e.png">|
VideoCollectionView 내 타이틀이 길어지더라도 타이틀이 제 자리를 지키도록 개선
|변경 전|변경 후|
|---|---|
|![](https://user-images.githubusercontent.com/39216546/202905834-9785c83f-0be3-4929-8f44-6f42ce7b1579.png)|<img width="600" alt="image" src="https://user-images.githubusercontent.com/39216546/202922974-12c86b5a-832b-476d-bc2c-1f4c2bc5f9b7.png">|
- UnderlinedTextField 모듈 …
=> [#215, #217] design - 날짜, 클라이밍장 정보 입력, 편집 UI 수정 + 기타 기능 수정

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift
1. 아이폰8같은 작은 화면에도 잘 보이게 수정하였습니다.
- #254
| 아이폰 8| 아이폰14 프로맥스 |
|---|---|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/72395020/203487539-1a7538f0-34ef-403a-be99-7a7d9699dd64.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/72395020/203487625-5c1d55b5-40bb-45e2-b891-2aba14a0c4a6.png">|
- 빠른 출시를 위하여 테이프로 구멍을 막은 느낌이 있지만 완료되었습니다!
- enum이나 패딩뷰를 사용하여 기기대응을 진행하는 방법도 있을것 같습니다.
- 감사합니다
Close #254
=> [#254] fix - 레벨 수정 뷰 기기대응

OrrRock/OrrRock/MainViewController.swift
1. 기존 MainViewController에 존재하던 routeFinding과 관련된 항목 주석 처리
2. 1.1.0 버전을 위하여 일시적으로 rootVC tabBarItem의 수를 2개로 수정
- #261
```
// MainViewController.swift
let myActivityViewController = MyActivityViewController()
let homeViewController = HomeViewController()
//        let routeFindingController = UIViewController()
// Tab Bar의 아이템 생성
let myActivityItem = UITabBarItem(title: "내 활동", image: UIImage(named: "tabbar mypage icon"), tag: 0)
let homeItem = UITabBarItem(title: "기록", image: UIImage(named: "tabbar home icon"), tag: 1)
//        let routeFindingItem = UITabBarItem(title: "루트파인딩", image: UIImage(named: "tabbar routefinding icon"), tag: 2)
// 각 뷰 컨트롤러에 아이템 할당
myActivityViewController.tabBarItem = myActivityItem
homeViewController.tabBarItem = homeItem
// …
```
=> [#261] hotfix - Release 버전 관리를 위한 MainViewController TabBarItem 수정

OrrRock/OrrRock/Utils/ColorPickerView.swift
1. 기존 선택된 상태의 변화가 흰색 테두리가 생기는 것이 가시성이 좋지 않아
2. 선택된 색상의 테두리가 생기는것으로 수정 했습니다.
- #264 
https://user-images.githubusercontent.com/103024840/203731008-1e7be89a-9739-45f4-b6de-ab1c32daa595.mov
https://user-images.githubusercontent.com/103024840/203730728-9707f3b9-67e0-4ee0-9bb1-4fd030c84dfe.mov
- 선택된 레이블이 넘어갈때 살짝 어색해 보이는 부분은 개선 방법은 찾고 있으나 기존 피커 커스텀을 해야 하는 부분이라
- 지금 당장 수정은 어려울듯 합니다.
- 하지만 그래도 저에게 한계란 없습니다.
Close #264
=> [#264] fix  - 컬러피커뷰의 선택 상태 개선을 했습니다.

OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift, OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
1. RouteInformation 클라이밍장 이름 수정 메소드 분리 및 구현
2. RouteInformation 클라이밍 데이터 추가 일자 수정 메소드 분리 및 구현
3. RouteInformation 클라이밍 문제 난이도 및 도전 상태 수정 메소드 분리 및 구현
- #268 
- **RouteDataManager.swift**: UI 계층에서 실제로 사용될 메소드가 위치합니다.
```swift
// RouteDataManager.swift
func updateRouteDataWrittenDate(to date: Date, of routeInformation: RouteInformation) {
coreDataDAO.updateRouteInformationDataWrittenDate(date: date, routeInformation: routeInformation)
}
func updateRouteGymName(to gymName: String, of routeInformation: RouteInformation) {
coreDataDAO.updateRouteInformationGymName(gymName: gymName, routeInformation: routeInformation)
}
func updateRouteLevelAndStatus(statusTo status: Bool, levelTo level: Int, of routeInformation: RouteInformation) {
coreDataDAO.updateRouteInformationLevelAndStatus(status: …
```
=> [#268] fix - RouteFindingDataManager RouteInformation 데이터 수정 메소드 분리

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Extensions/UINavigationController+.swift, OrrRock/OrrRock/MyActivity/MyActivityViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingViewController.swift, OrrRock/OrrRock/Upload/DateSettingViewController.swift, OrrRock/OrrRock/Upload/GymSettingViewController.swift, OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift, OrrRock/OrrRock/Utils/CustomBackBarButtomItem.swift, OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift, OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionViewController.swift, OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
간단한 이슈인줄 알았는데 내용이 조금 복잡해져서 오래 걸렸습니다.
설명이 길어도 양해 부탁드려요.
https://stackoverflow.com/questions/31731751/disable-swipe-back-gesture-in-swift
```swift
navigationController?.interactivePopGestureRecognizer?.isEnabled  = 
```
문제는 저코드는 자신의 뷰에서만 동작하고 사라지는 코드가 아닌 전체적인 앱의 모든 뷰에 영향을 줍니다.
해당 코드는 앱의 여러곳에서 사용되고 있었습니다.
해당 파일은 뒤로가기 영역확장을 위해 제작 되었습니다.
하지만 네비게이션컨트롤러에 기존 back버튼을 삭제 하게 되면 해당 제스쳐 또한 같이 사라지게 됩니다.
때문에 UINavigationController을 extension하여 해당 문제를 해결하였습니다.
```swift 
navigationController?.navigationBar.backgroundColor = .orrWhite
```
네비게이션 바의 백그라운드 색상 또한 한번 변경하면 계속 값이 유지 되기 때문에
색상을 설정해주는 코드가 한번 실행 되면 제스쳐를 사용해 뒤로가기를 할 때
바영역에 색이 남아 어색하게 보이는 이슈도 있었습니다. (이슈영상에서는 안보임)
해당 이슈
https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-8bit/issues/241
이슈에서 보이는 오류 발생 방법은 다음과 같습니다.
1. 제스쳐를 통해 뒤로가기를 할때 키보드가 튀어나옴
=> …
=> [#241] fix 앱의 전체적인 부분에서 뒤로가기 버튼 및 뒤로가기 제스쳐 수정

OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift, OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
1. `RouteFindingMainViewController`에서 필요한 도전 상태 변경 메소드 구현
- #280
- 기존 코드의 경우, `RouteFindingFeatureViewController`에서 문제 난이도, 도전 상태를 동시에 변환가능한 메소드만 존재하였으나, `RouteFindingMainViewController`에서 도전 상태"만" 바꾸는 메소드가 필요하다는 요청에 의해 아래의 코드가 새롭게 추가되었습니다.
```swift
// RouteCoreDataDAO.swift
func updateRouteInformationStatus(status: Bool, routeInformation: RouteInformation) {
guard let id = routeInformation.id else { return }
let request = RouteInformation.fetchRequest()
request.predicate = NSPredicate(format: "id == %@", id as CVarArg)
do {
let info = try context.fetch(request)
if let tempInfo = info.first {
tempInfo.setValue(status, forKey: "isChallengeComplete")
}
} catch {
print("CoreDataDAO UpateRoute Method \(error.localizedDescription)")
}
}
```
```swift
// RouteDataManager.swift
func …
```
=> [#280] feat - RouteDataManager 도전 상태 변경 메소드 구현

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Home/HomeViewController.swift, OrrRock/OrrRock/MyActivity/MyActivityViewController.swift, OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift, OrrRock/OrrRock/Upload/DateSettingViewController.swift, OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionViewController.swift, OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
1. 영상 선택 및 편집화면에서 전체선택 버튼이 변경되지 않는 이슈 해결 
2. 다른탭 전환시 상단에 여백이 생기는 이슈 해결
3. 기록 -> 목록형 -> 영상 상세 -> 이전페이지 시 목록형의 탭바영역이 살아 있는 이슈 해결 
아래의 코드는 SceneDelegate에 존재하는 코드입니다.
```swift
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
guard let windowScene = (scene as? UIWindowScene) else { return }
window = UIWindow(windowScene: windowScene)
window?.backgroundColor = .black
// MainViewController를 UINavigationController로 만들어 사용중
window?.rootViewController = UINavigationController(rootViewController: MainViewController())
window?.makeKeyAndVisible()
}
```
간단하게 설명하면 MainViewController() 는 탭바를 가지고 있는 VC이고 이는 네비게이션 컨트롤러로 설정이 되어 있습니다.
때문에 모든 네비게이션 전환시 MainViewController()위에 …
=> [#284] fix 상단 여백 발생 이슈 및 하단 탭바 영역 이슈 해결

OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+AVCapturePhotoCaptureDelegate.swift, OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift, OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
1. UIImage Type으로 들고올 수 없는 사진에 대해 처리하기
2. iCloud 및 네트워크 환경을 사용해야하는 사진에 대한 처리하기
2 - a. 네트워크 환경을 사용해야하는 경우, Loading Indicator 넣기
3. 카메라를 사용하는 경우, 정상적으로 사진을 찍었음에도 사진이 불러와지지 않는 에러 해결하기
4. 카메라 버튼 터치 시, 다른 버튼과의 Interaction 제한
- #289
**UIImage Type으로 들고올 수 없는 사진에 대한 처리**
```swift
// RouteFindingCameraViewController.swift line.157 - line.158
var config = PHPickerConfiguration(photoLibrary: photoLibrary)
config.filter = .all(of: [.images, .not(.panoramas), .not(PHPickerFilter.playbackStyle(.imageAnimated))])
```
- PHPickerConfiguration의 filter를 통해 UIImage로 불러올 수 없는 자료를 제한적으로 보여주도록 구현했습니다.
- 도움을 주신 류하 @RuyHa 감사합니다!
**iCloud 및 네트워크 환경을 사용해야하는 사진에 대한 처리**
- `PHImageRequestOptions`의 `isNetworkAccessAllowed`를 `true`로 변환합니다.
- 도움을 주신 꼬마 @hminkim 감사합니다!
```swift
// …
```
=> [#289] fix - RouteFindingCameraViewController 오류 수정

OrrRock/OrrRock/Extensions/String+.swift, OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift, OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
1. `generateCardViewThumbnail` 메소드 매개변수 설정
2. `RouteFindingSectionViewController thumbnail` 화질 개선
3. `RouteFindingDetailViewController thumbnail` 화질 개선
- #338
**수정된 메소드**
- 시그니처 변경문 추가
```swift
// 기존
func generateCardViewThumbnail() -> UIImage?
// 변경
func generateCardViewThumbnail(targetSize: CGSize = CGSize(width: 500, height: 500)) -> UIImage?
```
**`RouteFindingSectionViewController thumbnail` 화질 개선**
|기존|수정|
|:---:|:---:|
|![_1](https://user-images.githubusercontent.com/96641477/204997540-8e7fe973-23e6-4130-bb8b-9887f87b3221.jpeg)|![_3](https://user-images.githubusercontent.com/96641477/204997552-be6ff36a-d68c-4cda-a648-20b846bec50a.jpeg)|
**`RouteFindingDetailViewController thumbnail` 화질 개선**
|기존|수정|
|:---:|:---:|
|![_2](https://user-images.githubusercontent.com/96641477/204997550-622 …
=> [#338] feat - 루트파인딩 화면 내 이미지 화질 개선

OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
1. `RouteFindingCameraViewController`에 배경 색상을 설정했습니다.
- #352 
**`RouteFindingCameraViewController`에 `UIColor.black`으로 배경색상을 설정했습니다.**
- ♥️
Close #352
=> [#352] - fix 루트파인딩 업로드 카메라 뷰 배경 삽입

OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
1. 루트파인딩 메인 뷰 썸네일과 detailView 컨텐츠 불일치를 해결했습니다.
- #357 
- 감사합니다.
Close #357
=> [#357] fix - 루트파인딩 메인 뷰 썸네일과 detailView 컨텐츠 불일치 

OrrRock/OrrRock/AppDelegate.swift
1. 탭바 색상 변경
- #355
|수정 전|수정 후|
|---|---|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/205042697-4a1e383e-71c7-4336-acee-3f193828fac0.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/72395020/205083762-cc2356cf-6d46-4a41-9b6e-2fa179d23d83.jpeg">|
- ios 15에 들어서면서 scrollEdgeAppearance를 따로 지정해주지 않으면 탭바가 투명한색으로 변경되는 기능이 추가가되었습니다. 이를 해결하기 위해 appdelegate부분에 전체적으로 uitabbar 의 apperance를 지정해주었습니다.
- 참고 (https://stackoverflow.com/questions/69467580/transparent-tabbar-when-popping-child-navigationview-ios-15)
- 감사합니다.
Close #355
=> [#355] fix - tabbar color 를 변경하였습니다.

OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
1. 이미지 모서리 라운딩 크롭되어 저장되고 있는 문제 해결
- 기존에 `previewImageView`를 저장하여 뷰에 띄워주는 `cornerRadious`가 적용된 이미지가 저장되었음
- `UIImageView`였던 `previewImageView`에서 `UIImage`로 다운캐스팅 한 이미지를 저장 시키게 로직 수정
2. 기존 이미지가 하나만 저장되는 이슈 해결
- 기존에 우측 상단 저장 버튼으로 `previewImageView`에 띄워준 이미지 하나만 저장하였음
- 기획팀과의 의논 후 <u>기획 의도와 맞지 않다고 판단</u>하여 모든 루트파인딩 이미지를 저장하는 기능 추가
- 우측 상단 저장 버튼 클릭으로 이미지를 하나만 저장할 것인지 모두 저장할 것인지 `ActionSheet`를 띄워주게 변경
- "묶음사진 전체 저장"을 선택 시 `pageImages`의 모든 이미지들을 저장
- "이 사진만 저장"을 선택 시 `previewImageView`의 이미지만 저장
3. 이미지 저장 플로우의 변경에 따른 토스트 메세지의 내용 변경
- "묶음사진 전체 저장"을 선택 시 -> "모든 루트파인딩을 사진에 저장했습니다" 라는 토스트메세지 출력
- "이 사진만 저장"을 선택 시 -> "이 루트파인딩을 사진에 저장했습니다" 라는 토스트메세지 출력
- #350 
|액션시트 출력|"묶음 사진 전체 저장" 토스트메세지|"이 사진만 저장" 토스트메세지|
|:---:|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/45965405/205076519-0566 …
=> [#350] feat - 루트파인딩 저장하기 뷰 내 디테일 수정

OrrRock/OrrRock/CoreData/RouteFinding/RouteDataDraft.swift, OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
**1. X버튼 Alert 만들기**
- #356
**- Alert 메소드 `showExitAlert` 구현**
```swift
func showExitAlert() {
let optionMenu = UIAlertController(title: "저장하지 않고 나가기", message: "지금 나가면 변경 사항이\r\n삭제됩니다.", preferredStyle: .alert)
let deleteAction = UIAlertAction(title: "삭제", style: .destructive) {_ in
self.dismiss(animated: true, completion: nil)
}
let cancelAction = UIAlertAction(title: "취소", style: .cancel)
optionMenu.addAction(deleteAction)
optionMenu.addAction(cancelAction)
self.present(optionMenu, animated: true, completion: nil)
}
```
**- Sketch의 문구가 두 줄로 나뉘어 있어 줄을 두 개로 나누어 처리했습니다.**
```
message: "지금 나가면 변경 사항이\r\n삭제됩니다."
```
|Sketch 기반 디자인|실제 구현 사항|
|:---:|:---:|
|<img width="264" alt="image" src="https://user-images.githubusercontent.com/39216546/205043157-00854a54-5cb8-425e-b7b8-45c85061e83f.png">| …
=> [#356] fix - 루트파인딩 기능 뷰 내 X 버튼의 Alert 추가

OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift, OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController+CollectionViewExtensions.swift, OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift, OrrRock/OrrRock/RouteFindingDetail/RoutefindingDetailViewController+UIPageViewControllerExtensions.swift
**1. `RouteFindingDetailViewController` 의 `PageViewController` 오류 수정**
- #359 
- `viewDidLoad` 및 `lazy var routePageViewController`에서 사용하던 `PageViewController`의 첫번째 VC를 지정해주는 구문 제거 후 정상 동작하는 것을 확인했습니다.
- 자러가보겠습니다 :)
Close #359
=> [#359] fix - 루트파인딩 디테일 페이지 수, 썸네일 수 불일치 개선

OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift, OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
1. 루트 파인딩 메인뷰 모달 높이 이슈가 있습니다. 
앱이 백그라운드로 진입하고 재진입시에 바텀 옵션뷰 높이가 의도하지 않았던 높이로 설정됩니다.
2. 임시방편으로 userdefault를 사용하여 값을 받아와 저장하였습니다.
- #367
- 감사합니다.
Close #367
=> [#367] fix - 루트 파인딩 메인뷰 바텀 옵션뷰 높이 이슈

OrrRock/OrrRock/AppDelegate.swift, OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift, OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift, OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
1. 세번째 뷰에서 파란 밑줄이 생기는 이슈 해결
- 가운데에 위치한 셀 (선택된 셀)에 `selecBar`가 생성되는 로직으로 구현되어있었음
- 처음 뷰가 로드될 때 세번째 있는 셀이 가운데에 있다가 뷰가 나타날 때 셀이 밀리면서 `selectBar`가 두개가 되는 이슈가 생김
- `animated` 파라미터를 `true`로 주면서 뷰가 밀리는 과정에서 `selectBar`도 함께 밀리게 구현함으로써 이슈 해결
- #372 
- 이슈 해결에 큰 도움을 주신 @sm-amoled 에게 감사를 드립니다~
Close #372
=> [#372] fix - 뷰 파란색 영역 중복 출현 이슈 해결

OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift, OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
1. RouteFindingFeatureViewController `multiply X` -> `xmark X`로 수정하기
2. RouteFindingCameraViewController `multiply X` -> `xmark X`로 수정하기
- #384
|RouteFindingCameraVC|RouteFindingFeatureVC|
|:---:|:---:|
|![IMG_3962](https://user-images.githubusercontent.com/96641477/205621807-f68cd2bb-a05e-4aff-b176-ecc27e8ffc11.PNG)|![IMG_3963](https://user-images.githubusercontent.com/96641477/205621818-f44dd133-7934-454b-9f62-ee9d7e9892ce.PNG)|
Close #384
=> [#384] design - RouteFinding X 버튼 SFSymbol로 교체
