OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift
1. `VideoInformation` 배열을 반환하는 메소드 `readData` 구현
- #15 
- Core Data 데이터 읽기를 위한 메소드 `func readData()`는 **CoreDataManager.swift**에서 확인가능합니다.
- 테스트 코드는 아래와 같습니다.
- CREATE 버튼 터치 시, CoreData Container에 새로운 Record가 하나씩 추가됩니다.
- READ 버튼 터치 시, CoreData에 저장된 모든 VideoInformation Record를 불러와 Print합니다.
- 코드 삽입 후 SceneDelegate의 rootViewController를 `TestViewController`로 변경 후 테스트가 가능합니다.
```
import UIKit
import SnapKit
class TestViewController: UIViewController {
lazy var createDataButton: UIButton = {
let button = UIButton()
button.setTitle("CREATE", for: .normal)
return button
}()
lazy var readDataButton: UIButton = {
let button = UIButton()
button.setTitle("READ", for: .normal)
return button
}()
override func viewDidLoad() {
super.viewDidLoad()
[
createDataButton,
readDataButton
].forEach({ …
```
=> [#15] feat - CoreDataManager 구현: READ

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Extensions/Date+.swift, OrrRock/OrrRock/Extensions/String+.swift
1.  Date to String 함수 생성
2. String to Date 함수 생성
- #35 
- timeToString을 할 시 시간을 무시한 날짜값만 String으로 변환됨
- stringToDate를 할 시 시간 값이 없어서 am 00:00으로 고정
-> 어플리캐이션 내에서 시간을 제외한 날짜만 다루고 있다는 점에서 일단은 이 함수로 활용
- 사진으로 첨부 한 활용법 숙지 후 사용 해주셨으면 좋겠습니다
- 00월 00일이 아닌 0월 0일로 출력되게 했습니다.
- ex) 09월 04일 (X) -> 9월 4일 
Close #35
=> [#35] feat - String타입과 Date타입간의 빈번한 데이터 포매팅에 대한 함수 작성

OrrRock/OrrRock/Extensions/Padding+.swift
=> [hotfix] 패딩오류 수정

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/MainViewController.swift, OrrRock/OrrRock/SceneDelegate.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift, OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift, OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
1. LevelAndPFEditView UI 작업 완료
2. VideoCollectionView + DetailVideoCollectionView + DateAndGymEditView + LevelAndPFEditView 연결 완료
- #48 
- @hminkim 디테일뷰 구현하시느라 수고하셨습니다.
Close #48
=> [#48] LevelAndPFEditView UI 완성 및 VideoCollectionVIew 연결 완료 

OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift, OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift, OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
1. 홈뷰의 네비게이션 연결 변경
- #60 
Close #60
=> [#60] fix - homeview 네비게이션 변경

OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift, OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController+.swift, OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController.swift, OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift, OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
1. TestCode 삭제
2. CustomDetailButton  initializer 구현
3. HomeViewController 내 발견된 오류 수정
- #68
Close #68
=> [#68] hotfix - CustomDetailButton 코드 수정

OrrRock/OrrRock/Views/UploadView/DateSettingViewController.swift
1. 이젠 오늘 날짜를 선택시 다른 날짜를 클릭후 돌아올 필요가 없습니다/
- #84 
작업영상 입니다.
https://user-images.githubusercontent.com/103024840/197951404-0dc195a3-81a7-428b-a032-80b259b0fd4b.mov
- 다른 날짜 선택에도 "업로드할 영상의 날짜를 선택해주세요" 문구가 바뀌지 않습니다
Close #84
=> [#84] fix 데이터피커 기본 값 수정

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Extensions/UIview+.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift, OrrRock/OrrRock/Views/UploadView/SwipeableCardView/LevelPickerView.swift, OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift, OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
1. Default 문제 레벨 설정 
- 금일 회의 내용과 같이 
(`V0 - V9까지의 레벨` **+ `선택안함` 옵션(LV: -1), 선택안함 옵션의 경우에는 수치에 포함하지 않는 형태로!
→ 레벨이 선택되지 않은 경우에는 사용자에게 보이는 화면에서 `V?` 로 Labeling)
코드를 수정하였습니다.
2. 기존 피커의 간단한 버그도 같이 수정 하였습니다.
- #104 
https://user-images.githubusercontent.com/103024840/200573849-5bf48fbd-63d7-40c6-a116-e390658fbfed.mp4
- 그런거 없습니다.
Close #104
=> [#104] fix Default 문제 레벨 설정 

OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
1. 영상업로드시 슬로우모션 비디오 업로드제한
- #132 
- 화2팅
- 
Close #132
=> [#132] hotfix 슬로우모션 비디오 업로드 제한

OrrRock/OrrRock/MainViewController.swift, OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewControllerFirst.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/DateAndGymEditViewController.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+DataSorting.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift, OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift, OrrRock/OrrRock/Views/VideoCollectionView/BasePaddingLabel.swift, OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewCustomCell.swift
1. dodo가 담당한 파일의 코드 스타일 리팩토링
- #135 
Close #이슈번호
=> [#135] refactor - 코드 인덴트 및 안쓰는 코드 수정

OrrRock/OrrRock/Upload/UIComponent/View/LevelPickerView.swift
- 레벨 피커 휠 선택시 완료 버튼을 누르지 않아도 레벨이 선택되어지도록 개선
- #155 
- delegate로 값 변경 전달 코드 한 줄 적었어요오~~
- 사랑해요
Close #155
=> [#155] fix - 레벨 선택 피커 사용성 개선

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/VideoDetail/VideoCollectionViewController.swift
1. VideoCollectionView에서 영상삭제후 영상 클릭시 영상 재생뷰로 이동이 되지 않던 버그 해결
- #180
- 감사합니다
Close #180
=> [#180] fix - 영상삭제시 버그 해결

OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell+CollectionViewExtensions.swift, OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift, OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
1. HomeView Thumbnail Image Cell 내의 이미지 사이즈 조정
2. HomeView Thumbnail Collection View 의 여백 Sketch에 맞게 수정
- #195
1. 초록색 라인 개선
2. 좌우 패딩 및 영상 갯수 개선
Close #이슈번호
=> [#195] fix - HomeView 내 Thumbnail 관련 UI 수정

OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift, OrrRock/OrrRock/SwipeOnboarding/EmptyBackgroundView.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFifthViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFirstViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift
1. 컬러값 및 패딩 에셋 변경사항 작업 사항과 동시간때 이루어진 작업에서는 값 변경이 적용되지 않아 빌드가 되지 않던 문제를 해결 했습니다.
2. 바뀐값으로 다 수정 하긴 했으나 해당 뷰 작업 하시는 분들은 한번씩 더 확인 바랍니다.
- #203
컨플릭이 안나서 문제가 없다고 생각 했는데... 저런...
Close #203
=> [#203] hotfix 컬러,패딩 변경에 따른 대응값 수정

OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
1. VideoDetailView의 UI를 변경된 UI에 맞춰 수정하였습니다.
- #218 
|수정 전|수정 후|
|---|---|
|<img width="300" height ="600" alt="image" src="https://user-images.githubusercontent.com/72395020/203031614-06ea6376-215b-47da-a804-404d3fbb6ea5.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/72395020/203030987-6237d638-92ee-4444-8883-61d9174ad86e.png">|
- 스크린샷에서 확인할 부분은 툴바의 변화입니다!
- 감사합니다
Close #218
=> [#218] fix - VideoDetailView toolbar UI 변경

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Utils/ColorPickerView.swift, OrrRock/OrrRock/Utils/TestColorPickerViewController.swift
1. 컬러피커를 제작 했습니다.
2. 디테일한 수정및 코드 정렬은 추후 다시 해서 올리겠습니다. (급해서..)
- #250
https://user-images.githubusercontent.com/103024840/203381330-0b227a77-85a7-45dd-98ac-9285a95fb3ce.mp4
-진짜 저에겐 한계란 없습니다.
- 화이팅
Close #250
=> [#250] feat 컬러피커 제작완료

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Extensions/UIImage+.swift, OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift, OrrRock/OrrRock/Home/Cell/HomeTableViewListCell.swift, OrrRock/OrrRock/Home/HomeViewController.swift
- HomeView 내 버튼 크기 조정
- 앨범형 카드 상하 여백 조정
- 앨범형 카드 레이블 간의 여백 조정
- 목록형 셀 디바이더 길이 조절
- 목록형 셀 Header 디바이더 제거
- #249 
|앨범형 기존|앨범형 개선|목록형 기존|목록형 개선|
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/39216546/203386560-013d0b29-be6d-4ac8-95e4-aeba256d8c7d.png)|![image](https://user-images.githubusercontent.com/39216546/203386084-92a6138b-3f11-4a7a-85aa-d4c913ca911c.png)|![image](https://user-images.githubusercontent.com/39216546/203386610-a736f73e-9b1d-4734-9c5c-d15915082b9b.png)|![image](https://user-images.githubusercontent.com/39216546/203386166-c3de9774-1850-4aa8-a64d-71b36d313e7c.png)|
- 사랑해요
Close #249
=> [#249] design - HomeView 린다 디자인 피드백 반영 수정

OrrRock/OrrRock/MyActivity/MyActivityViewController.swift, OrrRock/OrrRock/MyActivity/SwiftUIChartView/HomeGymChartView.swift
1. HomeGymChartView 보여주는 차트 수정
2. HomeGymChartView 컬러 배열 반환 수정
- #256 
유효한 데이터가 없을 때 BarMark 자체를 생성하지 않도록 로직을 개선. 
```swift
Chart {
ForEach(mostFrequentlyVisitedGymList, id: \.self.0) { data in
if data.0 != "" {
BarMark(x: .value(data.0, data.1))
.foregroundStyle(by: .value("color", data.0))
}
}
if totalGymVisitedDate - mostFrequentlyVisitedGymList[0].1 - mostFrequentlyVisitedGymList[1].1 - mostFrequentlyVisitedGymList[2].1 != 0 {
BarMark(x: .value("기타", totalGymVisitedDate - mostFrequentlyVisitedGymList[0].1 - mostFrequentlyVisitedGymList[1].1 - mostFrequentlyVisitedGymList[2].1))
.foregroundStyle(by: .value("color", "기타"))
}
}
```
유효한 데이터가 없을 때 ColorSet을 조건에 따라 다르게 생성하도록 [기타 클라이밍장 데이터가 없을 때] 조건 추가
```swift
func createColorSetForChart() -> KeyValuePairs<String, Color> {
// KeyValuePairs는 …
```
=> [#256] fix - MyActivityView 진입 시 3개 이하의 데이터일 때 앱 크래시 수정

OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift, OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageView.swift, OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewCell.swift, OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewFlowLayout.swift, OrrRock/OrrRock/SceneDelegate.swift
#272 PR의 코드리뷰를 반영하여 코드를 수정하였습니다!
1. final, private 지정
2. 일부 코드 로직 수정
3. 버튼 색상 지정 값 수정
- 깜빡했어요,,, 12시가 넘은지라 피곤한가봐요 ㅎㅎ
- 사랑해요
=> [#225] fix - PR 코드리뷰 반영 코드 수정

OrrRock/OrrRock.xcodeproj/project.pbxproj
1. 번들 아이디 및 계정 정보로 인한 오류 해결 
2. 
- #282
미안하다~~~~~!!!
Close #282
=> [#282] hotfix - 오류 수정

OrrRock/OrrRock.xcodeproj/project.pbxproj, OrrRock/OrrRock/Home/HomeViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift, OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift, OrrRock/OrrRock/Upload/GymSettingViewController.swift, OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift, OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift, OrrRock/OrrRock/Utils/NewLevelPickerView.swift, OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift, OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
1. 영상 편집 화면에 새로은 레벨 피커를 적용 했습니다.
2. 레벨피커의 다크모드 대응을 추가했습니다.
- #288 
https://user-images.githubusercontent.com/103024840/204466590-8cc15dc3-c308-4291-aec2-5242e3a07867.mov
- 저에게 한계란 없습니다.
- 화이팅~~
Close #288
=> [#288] fix - 영상 편집 화면의 레벨 피커 적용

OrrRock/OrrRock/Utils/ColorPickerView.swift, OrrRock/OrrRock/VideoDetail/ExportViewController.swift
1. 디자인이 변경된 컬러 피커뷰를 반영 했습니다.
- #293
https://user-images.githubusercontent.com/103024840/204488234-5dc3e576-c6fb-442a-9cce-5f0ca9ea9c85.mov
- 류이했 완료 했습니다.
Close #293
=> [#293] fix 컬러피커뷰 백그라운드 적용 완료

OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift, OrrRock/OrrRock/SceneDelegate.swift
머지오류해결
- #307
- 코드 or 스크린샷 or 동영상
- 작업의 결과물이 따로 존재하지 않는 경우에는 기록 X
Close #307
=> [#307] hotfix  오류수정

OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
루트파인딩 메인뷰의 토스트 메시지 스피드를 조절하였습니다.
- #311
https://user-images.githubusercontent.com/72395020/204752839-ddb3534c-471f-45ed-bff2-9f64f220cee4.MP4
- 감사합니다
Close #311
=> [#311] fix - 토스트 메세지의 스피드를 조절하였습니다.

OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureButton.swift
1. 코드 가독성 정리하다가 빠트린 코드 한 줄을 수정했습니다.
- #317
```swift
import Foundation → import UIKit
```
- 죄송해요
Close #317
=> [#317] HOTFIX - 핫픽스 코드 수정

OrrRock/OrrRock/RouteFinding/RouteModalViewController.swift
1. 루트파인딩 메인 뷰 textalignment 수정
- #323
|수정 전|수정 후|
|---|---|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/72395020/204848312-6e697afd-5026-41cb-a3a2-b48da65b59f2.jpeg">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/72395020/204848438-e33fd510-dbea-4534-b5b6-8264a5eaa517.jpeg">|
- 감사합니다.
Close #323
=> [#323] fix - 루트파인딩 메인 뷰 textalignment 수정

OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift, OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
1. 카메라 사용권한 체크 후 refresh 에러 해결
- 도도 @commitcomplete 가 발견하신 버그를 Handling하는 과정에서 부가적으로 발견된 오류들을 함께 묶어 처리했습니다.
2. 다크모드, 라이트모드 전환 시 버튼 색상이 변경되는 에러 해결
3. 사진 접근 권한이 `모든 사진 허용`이 아닌 경우에 대한 처리
- #320 
**1. 카메라 사용권한 체크 후 refresh 에러 해결**
- `RouteFindingCameraViewController`에서 앱 실행 후 최초로 카메라를 연 후, 카메라 권한 설정을 `허용`할 시 카메라 화면이 출력되지 않는 에러 해결
- `viewDidLoad`에서 카메라 관련 세션 체크를 위한 메소드 `authorizateCameraStatus`에서 카메라 세션 세팅 메소드(`setupCameraSession`)를 간접적으로 호출하는 것이 아니라 직접 호출합니다.
```swift
// RouteFindingCameraViewController.swift
// 기존 코드
authorizateCameraStatus()
// 변경된 코드
setupCaptureSession()
```
**2. 다크모드, 라이트모드 전환 시 버튼 색상이 변경되는 에러 해결**
- 기존 코드의 경우 다크모드, 라이트모드에 따라 변경되는 `Orr` 색상을 사용하였으나, `RouteFindingCameraViewController`의 버튼의 색상은 모드에 영향을 받지 않게 만들기 위해 수정
```swift
// RouteFindingCameraViewController.swift
// 기존 …
```
=> [#320] fix - 카메라 사용권한 체크 후 refresh 이슈 + 부가적으로 발견된 카메라 관련 오류

OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift, OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewFlowLayout.swift
1. #314 이슈에 대한 PR의 리뷰 수정 요청 커밋이 push되지 않은 이슈에 대한 재 PR
- #314 #330 
- 죄송합니다 하핫
Close #330
=> [#330] style - push하지 않은 수정 커밋 재 PR

OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController+GestureExtensions.swift, OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
**1. `RouteFindingDetailViewController` 상하 스와이프 액션 추가**
- #334 
- **기존에 이미 `RouteFindingDetailViewController`의 Extension으로 메소드가 존재했기 때문에 많은 코드 작업이 이루어지지 않았습니다.
`RouteFindingDetailViewController` `init`에 제스처 추가를 위한 메소드 추가**
```swift
//  RouteFindingDetailViewController.swift
init(routeDataDraft: RouteDataDraft) {
self.routeDataDraft = routeDataDraft
super.init(nibName: nil, bundle: nil)
setUpLayout()
setNavigationBar()
setUpPageViewController()
setUpCollectionView()
addUIGesture() // 추가된 코드
loadPageViewControllerList()
let tapgesture = UITapGestureRecognizer(target: self, action: #selector(respondToTapGesture(_:)))
view.addGestureRecognizer(tapgesture)
}
```
- `UISwipeGestureRecognizer`의 action으로 할당해주는 `respondToTapGesture` 메소드에 `위에서 아래`로 스와이프를 하는 경우, Info창을 내리기 위한 `else`문을 추가
```swift …
```
=> [#334] feat - 루트파인딩 디테일뷰 내 정보 뷰 표시 등의 제스처 구현

OrrRock/OrrRock.xcodeproj/project.pbxproj
1. Display Name 수정
2. 앱 배포 버전 수정
3. 앱 기본 언어 수정
- #375
- Display Name: `OrrRock` -> `ORRROCK`으로 수정
- 앱 배포 버전 `1.2.0`으로 수정
- 앱 기본 언어 `en` -> `kr`로 수정
- ♥️
Close #375
=> [#375] chore - 1.2.0 릴리즈 버전 관리

OrrRock/OrrRock.xcodeproj/project.pbxproj
1. `Sprint.3` 추가 버그 픽스 및 로직 개선
2. 나의 활동 페이지 카드 제스처 추가
- #399 
- 앱 배포 버전 `1.2.2`으로 수정
- ♥️
Close #399
=> [#399] release - 1.2.2 릴리즈 버전 관리
